# Generated by Django 4.2.7 on 2023-11-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_front_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installation_date', models.DateField()),
            ],
        ),
    ]
